1. Setup Tensorflow and PyTorch based on the instructions in `./setup/README.md`

In [3]:
try:
    import torch
    print(f'Tensor: {torch.tensor([10, 10])}')
    print(f'PyTorch version: {torch.__version__}')    
    print('Succeeded')
except:
    print("Didn't succeed")

Tensor: tensor([10, 10])
PyTorch version: 2.3.1
Succeeded


In [6]:
try:
    import tensorflow as tf
    print(f'Tensor: {tf.constant([10, 10])}')
    print(f'Tensorflow version: {tf.__version__}')    
    print('Succeeded')
except:
    print("Didn't succeed")

Tensor: [10 10]
Tensorflow version: 2.17.0
Succeeded


## 2.
## a.

In [7]:

# Define two vectors
vector1 = torch.tensor([1.0, 2.0, 3.0])
vector2 = torch.tensor([4.0, 5.0, 6.0])

# Calculate the dot product
dot_product = torch.dot(vector1, vector2)

print(f"The dot product of {vector1.tolist()} and {vector2.tolist()} is {dot_product.item()}")


The dot product of [1.0, 2.0, 3.0] and [4.0, 5.0, 6.0] is 32.0


## b.

In [8]:
# Define two 2x2 matrices
matrix1 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
matrix2 = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

# Calculate the matrix multiplication
result = torch.matmul(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nMatrix multiplication result:")
print(result)

Matrix 1:
tensor([[1., 2.],
        [3., 4.]])

Matrix 2:
tensor([[5., 6.],
        [7., 8.]])

Matrix multiplication result:
tensor([[19., 22.],
        [43., 50.]])


## 3.
## a.

In [9]:
# Define two vectors
vector1 = tf.constant([1.0, 2.0, 3.0])
vector2 = tf.constant([4.0, 5.0, 6.0])

# Calculate the dot product
dot_product = tf.tensordot(vector1, vector2, axes=1)

print(f"The dot product of {vector1.numpy()} and {vector2.numpy()} is {dot_product.numpy()}")

The dot product of [1. 2. 3.] and [4. 5. 6.] is 32.0


## b.

In [10]:
# Define two 2x2 matrices
matrix1 = tf.constant([[1.0, 2.0], [3.0, 4.0]])
matrix2 = tf.constant([[5.0, 6.0], [7.0, 8.0]])

# Calculate the matrix multiplication
result = tf.matmul(matrix1, matrix2)

print("Matrix 1:")
print(matrix1.numpy())
print("\nMatrix 2:")
print(matrix2.numpy())
print("\nMatrix multiplication result:")
print(result.numpy())

Matrix 1:
[[1. 2.]
 [3. 4.]]

Matrix 2:
[[5. 6.]
 [7. 8.]]

Matrix multiplication result:
[[19. 22.]
 [43. 50.]]
